name: Set Maven environment variables.

inputs:
  VAULT_URL:
    required: true
    description: 'The URL of the Vault server'
  VAULT_SECRET_PATH:
    required: true
    description: 'The path to the secret in Vault'
  VAULT_ROLE_ID:
    required: true
    description: 'The role ID for the AppRole authentication method'
  VAULT_SECRET_ID:
    required: true
    description: 'The secret ID for the AppRole authentication method'

runs:
  using: "composite"
  steps:
    - name: Set REPOSITORY_NAME
      uses: NationalLibraryOfNorway/tekst-workflows/.github/action/set-repo-name@feat/set-maven-environment-variables

    - name: Import environment variable secrets
      id: import-secrets
      uses: hashicorp/vault-action@v3
      with:
        url: ${{ inputs.VAULT_URL }}
        method: approle
        roleId: ${{ inputs.VAULT_ROLE_ID }}
        secretId: ${{ inputs.VAULT_SECRET_ID }}
        secrets: |
          ${{ inputs.VAULT_SECRET_PATH }}/${{ env.REPOSITORY_NAME }}-stage * ;
          ${{ inputs.VAULT_SECRET_PATH }}/keycloak-nbauth-tekst *;

    - name: Write secrets to environment variables
      shell: bash
      run: |
        touch secrets.json
        echo '${{ toJson(steps.import-secrets.outputs) }}' >> secrets.json
        jq -r 'to_entries[] | .key + "=" + .value' secrets.json >> $GITHUB_ENV
        rm secrets.json