name: Set REPOSITORY_NAME variable
description: Sets an env variable REPOSITORY_NAME to the name of the repository

runs:
  using: "composite"
  steps:
    - name: Set REPOSITORY_NAME variable
      shell: bash
      run: |
        echo "REPOSITORY_NAME=$(echo $GITHUB_REPOSITORY | cut -d'/' -f2)" >> $GITHUB_ENVgit status
