name: Write secrets to .env
description: Set environment variables from Vault to .env. Useful for e.g. Next.js applications.

inputs:
  ENVIRONMENT:
    required: true
    description: 'Env name (stage/prod)'
  VAULT_URL:
    required: true
    description: 'The URL of the Vault server'
  VAULT_SECRET_PATH:
    required: true
    description: 'The path to the secret in Vault'
  VAULT_ROLE_ID:
    required: true
    description: 'The role ID for the AppRole authentication method'
  VAULT_SECRET_ID:
    required: true
    description: 'The secret ID for the AppRole authentication method'

runs:
  using: "composite"
  steps:
    - name: Set REPOSITORY_NAME
      uses: NationalLibraryOfNorway/tekst-workflows/.github/action/set-repo-name@main

    - name: Import environment variable secrets
      id: import-secrets
      uses: hashicorp/vault-action@v3
      with:
        url: ${{ inputs.VAULT_URL }}
        method: approle
        roleId: ${{ inputs.VAULT_ROLE_ID }}
        secretId: ${{ inputs.VAULT_SECRET_ID }}
        secrets: |
          ${{ inputs.VAULT_SECRET_PATH }}/${{ env.REPOSITORY_NAME }}-${{ inputs.ENVIRONMENT }} * ;
    

    - name: Set environment
      shell: bash
      run: |
        echo "${{ steps.import-secrets.outputs }}" > .env.production
        echo "--------- TESTING ---------"
        cat .env.production
        echo "--------- TESTING ---------"

#    - name: Write Vault secrets to JSON
#      shell: bash
#      run: |
#        echo "${{ toJSON(steps.import-secrets.outputs) }}" >> secrets.json
#        echo "--------- TESTING ---------"
#        cat secrets.json
#        echo "--------- TESTING ---------"


#    - name: Set environment variables
#      shell: bash
#      run: |
#        echo "${{ steps.import-secrets.outputs }}" >> ${{ inputs.ENV_FILE }}

#    - name: Set environment variables
#      shell: bash
#      run: |
#        echo "" >> .env
#        jq -r 'to_entries[] | .key + "=" + .value' secrets.json >> .env
#
#    - name: debug -- print .env
#      shell: bash
#      run: |
#        echo "--------- TESTING ---------"
#        cat .env
#        echo "--------- TESTING ---------"

#    - name: Cleanup
#      shell: bash
#      run: |
#        rm secrets.json