name: Write secrets to .env
description: Set environment variables from Vault to .env. Useful for e.g. Next.js applications.

inputs:
  ENVIRONMENT:
    required: true
    description: 'Env name (stage/prod)'
  VAULT_URL:
    required: true
    description: 'The URL of the Vault server'
  VAULT_SECRET_PATH:
    required: true
    description: 'The path to the secret in Vault'
  VAULT_ROLE_ID:
    required: true
    description: 'The role ID for the AppRole authentication method'
  VAULT_SECRET_ID:
    required: true
    description: 'The secret ID for the AppRole authentication method'
  FRAMEWORK:
    required: false
    description: 'The framework to use (e.g. nextjs, react, nodejs, hilla). Defaults to nextjs.'
    default: 'nextjs'

runs:
  using: "composite"

  steps:
    - name: Check for supported framework
      id: check-framework
      shell: bash
      run: |
        if [[ "${{ inputs.FRAMEWORK }}" != "nextjs" && "${{ inputs.FRAMEWORK }}" != "hilla" ]]; then
          echo "Unsupported framework: ${{ inputs.FRAMEWORK }}. Supported frameworks are: nextjs, hilla."
          exit 1
        fi

    - name: Set REPOSITORY_NAME
      uses: NationalLibraryOfNorway/tekst-workflows/.github/action/set-repo-name@main

    - name: Import environment variable secrets
      if: ${{ inputs.FRAMEWORK == 'nextjs' }}
      id: import-secrets-nextjs
      uses: hashicorp/vault-action@v3
      with:
        url: ${{ inputs.VAULT_URL }}
        method: approle
        roleId: ${{ inputs.VAULT_ROLE_ID }}
        secretId: ${{ inputs.VAULT_SECRET_ID }}
        secrets: |
          ${{ inputs.VAULT_SECRET_PATH }}/${{ env.REPOSITORY_NAME }}-${{ inputs.ENVIRONMENT }} * ;
          ${{ inputs.VAULT_SECRET_PATH }}/keycloak-nbauth-tekst * | NEXT_PUBLIC_ ;

    - name: Import environment variable secrets
      if: ${{ inputs.FRAMEWORK == 'hilla' }}
      id: import-secrets-hilla
      uses: hashicorp/vault-action@v3
      with:
        url: ${{ inputs.VAULT_URL }}
        method: approle
        roleId: ${{ inputs.VAULT_ROLE_ID }}
        secretId: ${{ inputs.VAULT_SECRET_ID }}
        secrets: |
          ${{ inputs.VAULT_SECRET_PATH }}/${{ env.REPOSITORY_NAME }}-${{ inputs.ENVIRONMENT }} * | VITE_ ;

    - name: Write secrets to .env
      shell: bash
      run: |
        touch secrets.json
        if [ ${{ inputs.FRAMEWORK }} == 'nextjs' ]; then
          ENV_FILE=.env
          echo '${{ toJson(steps.import-secrets-nextjs.outputs) }}' >> secrets.json
        elif [ ${{ inputs.FRAMEWORK }} == 'hilla' ]; then
          ENV_FILE='src/main/frontend/.env'
          echo '${{ toJson(steps.import-secrets-hilla.outputs) }}' >> secrets.json
        fi
        echo "" >> $ENV_FILE
        jq -r 'to_entries[] | .key + "=" + .value' secrets.json >> $ENV_FILE
        rm secrets.json