name: Set environment variables
description: Sets an env variable REPOSITORY_NAME and ARTIFACT_ID to the name of the repository

jobs:
  set-app-name:
    name: Set ENV
    runs-on: "composite"
    steps:
      - name: Set environment variables
        run: |
          echo "REPOSITORY_NAME=$(echo $GITHUB_REPOSITORY | cut -d'/' -f2)" >> $GITHUB_ENV
          echo "ARTIFACT_ID=$(grep -oP '(?<=<artifactId>).*?(?=</artifactId>)' pom.xml)" >> $GITHUB_ENV