name: SED values for kubernetes
description: Replace values in kubernetes yaml files

inputs:
  IMAGE_VERSION:
    required: true
    description: placeholder
  ENVIRONMENT:
    required: true
    description: placeholder
  HOST_URL:
    required: true
    description: placeholder
  HARBOR_URL:
    required: true
    description: placeholder


runs:
  using: "composite"
  steps:
    - name: Set REPOSITORY_NAME
      uses: NationalLibraryOfNorway/tekst-workflows/.github/action/set-repo-name@feat/set-dotenv-file
    - name: SED
      shell: bash
      run: |
        sed -i "s|<harbor_url>|${{ inputs.HARBOR_URL }}|g" k8s/${{ inputs.ENVIRONMENT }}/${{ env.REPOSITORY_NAME }}.yml
        sed -i "s|<version>|${{ inputs.image_version }}|g" k8s/${{ inputs.ENVIRONMENT }}/${{ env.REPOSITORY_NAME }}.yml
        sed -i "s|<host_url>|${{ inputs.HOST_URL }}|g" k8s/${{ inputs.ENVIRONMENT }}/${{ env.REPOSITORY_NAME }}.yml