name: Node build
description: 'Verify (lint, test) and build a node application'
inputs:
  NODE_VERSION:
    description: 'The version of Node.js to use'
    required: true
  SET_ENV:
    description: 'Whether to set the environment variables in a .env file'
    required: true
  ENVIRONMENT:
    description: 'The environment to deploy to (stage, prod)'
    required: true
  HEADLESS:
    description: 'Whether to run tests headless'
    required: true
  VAULT_URL:
    required: true
    description: 'The URL of the Vault server'
  VAULT_SECRET_PATH:
    required: true
    description: 'The path to the secret in Vault'
  VAULT_ROLE_ID:
    required: true
    description: 'The role ID for the AppRole authentication method'
  VAULT_SECRET_ID:
    required: true
    description: 'The secret ID for the AppRole authentication method'

runs:
  using: 'composite'
  steps:
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.NODE_VERSION }}
        cache: "npm"

    - name: Install dependencies
      shell: bash
      run: npm install

    - name: Linting
      shell: bash
      run: npm run lint

    - name: Create .env
      if: ${{ inputs.SET_ENV == 'true' }}
      uses: NationalLibraryOfNorway/tekst-workflows/.github/action/write-env-file-from-vault@ci/chrome-test
      with:
        ENVIRONMENT: ${{ inputs.ENVIRONMENT }}
        VAULT_URL: ${{ inputs.VAULT_URL }}
        VAULT_SECRET_PATH: ${{ inputs.VAULT_SECRET_PATH }}
        VAULT_ROLE_ID: ${{ inputs.VAULT_ROLE_ID }}
        VAULT_SECRET_ID: ${{ inputs.VAULT_SECRET_ID }}

    - name: Run unit tests
      if: ${{ inputs.HEADLESS == 'false' }}
      shell: bash
      run: npm run test

    - name: Install dependencies
      shell: bash
      run: |
        wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
        sudo dpkg -i google-chrome-stable_current_amd64.deb
        sudo apt-get install -f
        sudo dpkg -i google-chrome-stable_current_amd64.deb


    - name: Run unit tests headless
      shell: bash
      if: ${{ inputs.HEADLESS == 'true' }}
      run: npm run test:headless

    - name: Build application
      shell: bash
      run: npm run build