name: Build and publish Docker image

on:
  workflow_call:
    inputs:
      USE_HARBOR:
        required: true
        type: boolean
      ARTIFACT_FILE_NAME:
        required: true
        type: string
    secrets:
      VAULT_URL:
        required: true
      VAULT_SECRET_PATH:
        required: true
      VAULT_ROLE_ID:
        required: true
      VAULT_SECRET_ID:
        required: true

jobs:
  build-and-publish-docker-image:
    name: Create and push Docker image
    outputs:
      image_version: ${{ steps.meta.outputs.version }}
    runs-on: [ self-hosted-linux ]
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver: docker

      - name: Import harbor secrets from Vault
        if: ${{ inputs.USE_HARBOR }}
        id: import-secrets
        uses: hashicorp/vault-action@v3
        with:
          url: ${{ secrets.VAULT_URL }}
          method: approle
          roleId: ${{ secrets.VAULT_ROLE_ID }}
          secretId: ${{ secrets.VAULT_SECRET_ID }}
          secrets: |
            ${{ secrets.VAULT_SECRET_PATH }}/harbor * ;

      - name: Log in to Harbor # TODO setup dockerhub login
        if: ${{ inputs.USE_HARBOR }}
        uses: docker/login-action@v3
        with:
          registry: ${{ steps.import-secrets.outputs.HARBOR_URL }}
          username: ${{ steps.import-secrets.outputs.HARBOR_USERNAME }}
          password: ${{ steps.import-secrets.outputs.HARBOR_PASSWORD }}

      - name: Set REPOSITORY_NAME
        uses: NationalLibraryOfNorway/tekst-workflows/.github/action/set-repo-name@main

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ steps.import-secrets.outputs.HARBOR_URL }}/tekst/${{ env.REPOSITORY_NAME }} # TODO set image based on docker host
          tags: |
            type=semver,pattern={{version}}
            type=ref,event=branch
            type=ref,event=pr

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.ARTIFACT_FILE_NAME }}

      - name: Build image
        uses: docker/build-push-action@v5
        with:
          push: true
          context: .
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}